# Generated by Django 2.2.16 on 2022-08-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20220814_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Единица измерения'),
        ),
    ]
